import assert from 'node:assert/strict';
import { TeamMatch, teamTarget } from '../src/team-match.js';
import { HostCombat } from '../src/host-combat.js';
let count=0,time=0;
const check=(name,ok)=>{assert.ok(ok,name);console.log('PASS '+name);count++;};
const roster=new Map([['a',{team:'red'}],['b',{team:'blue'}]]);
const players=new Map([['a',{hp:110}],['b',{hp:110}]]);
const round=new TeamMatch({now:()=>time});round.startRound();
check('default target is 16, starting with a three second freeze',round.target===16&&round.phase==='freeze'&&round.view().left===3);
check('invalid round targets default safely', [0,-1,100,1.5,NaN,'16'].every(n=>teamTarget(n)===16)&&teamTarget(99)===99);
time=2.99;round.tick(roster,players);check('freeze cannot end early',round.phase==='freeze');
time=3;round.tick(roster,players);check('round has two minutes of live play',round.phase==='live'&&round.view().left===120);
players.get('b').hp=0;round.tick(roster,players);check('elimination awards one round, not a kill target',round.scores.red===1&&round.phase==='intermission');
round.tick(roster,players);check('dead roster cannot award the same round twice',round.scores.red===1);
for(let i=1;i<16;i++){
 time=round.deadline;round.tick(roster,players);players.get('b').hp=110;
 if(i===15)check('sides swap after 15 rounds',round.round===16&&round.view().swapped);
 time=round.deadline;round.tick(roster,players);players.get('b').hp=0;round.tick(roster,players);
}
check('16 round wins ends the match',round.phase==='over'&&round.winner==='red'&&round.scores.red===16);
const tied=new TeamMatch({now:()=>time,target:1});tied.startRound();time+=3;tied.tick(roster,players);
players.get('a').hp=0;tied.tick(roster,players);check('simultaneous elimination is a draw',tied.result==='draw'&&tied.scores.red===0&&tied.scores.blue===0);
time+=4;tied.tick(roster,players);players.get('a').hp=110;players.get('b').hp=90;time+=3;tied.tick(roster,players);time+=120;tied.tick(roster,players);
check('timeout uses remaining health when alive counts match',tied.winner==='red');
const empty=new TeamMatch({now:()=>time});empty.startRound();empty.tick(new Map([['b',{team:'blue'}]]),players);check('last opposing player leaving forfeits the match',empty.phase==='over'&&empty.winner==='blue'&&empty.result==='forfeit');
const equal=new TeamMatch({now:()=>time});players.get('b').hp=110;equal.startRound();time+=3;equal.tick(roster,players);time+=120;equal.tick(roster,players);check('equal health at timeout draws rather than favoring a team',equal.result==='draw');
let live=true,seq=0;
const c=new HostCombat({now:()=>time,enabled:()=>live,friendly:(a,b)=>a!==b&&b==='ally',regenerate:()=>false});
const setup=()=>{c.clear();live=true;c.add('a',[0,0,0]);c.add('b',[0,0,-10]);c.add('ally',[0,0,-2]);time+=3;};
const hit=(extra={})=>c.hit('a',{id:String(++seq),src:'rifle',target:'b',life:c.players.get('b').life,attackerLife:c.players.get('a').life,from:[0,1.6,0],point:[0,1.6,-10],aim:[0,0,-1],ray:[0,0,-1],...extra});
setup();check('honest shot with matching ray is accepted',hit().amount===19);
check('silent aim with conflicting aim and ray is rejected',hit({aim:[1,0,0]}).reason==='aim');
check('fabricated impact off the shot ray is rejected',hit({ray:[.03,0,-Math.sqrt(1-.03**2)]}).reason==='ray');
check('missing aim and non-unit ray are rejected',hit({aim:null}).reason==='aim'&&hit({ray:[0,0,-50]}).reason==='aim');
setup();c.players.get('a').snap=[0,0,0,Math.PI,0,0,64];check('fast flick is not judged against an older snapshot angle',hit().amount===19);
setup();check('team damage cannot bypass the central ledger',c.damage(c.players.get('ally'),110,'a')===0);
c.blast('a','mine',[0,1,-2],'mine');check('explosives cannot damage a teammate',c.players.get('ally').hp===110);
live=false;check('damage and hits are disabled between rounds',hit().reason==='round'&&c.damage(c.players.get('b'),110,'a')===0);
const a=c.players.get('a');const snap=c.snapshot('a',[30,0,0,0,0,0,64|32|128,110,10,0,0,0,0,0,a.life]);check('frozen snapshots cannot move or fire',snap[0]===0&&!(snap[6]&(32|128))&&snap[8]===0);
live=true;c.players.get('b').hp=50;time+=10;c.tick();check('team mode has no passive health regeneration',c.players.get('b').hp===50);
console.log(count+' team/aim rules checks passed');
